import { Router } from "express";
import * as authController from './auth.controller.js';
import validation from "../../midleware/validation.js";
import { LoginSchema, RegisterSchema } from "./auth.validation.js";
import { auth } from "../../midleware/auth.js";
import { asyncHandler } from "../../Utils/catchError.js";
const router = Router();
router.post('/userRegister',validation(RegisterSchema),asyncHandler(authController.Register));
router.post('/userLogin',validation(LoginSchema),asyncHandler(authController.Login));
router.get('/allUsers',auth,asyncHandler(authController.allUsers));
export default router;